version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: vendas_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: vendasdb
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - vendas-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: vendas_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - vendas-network

volumes:
  postgres-data:

networks:
  vendas-network:
    driver: bridge
